production:
  sitemap_generation:
    command: "system('bin/rails sitemap:refresh')"
    queue: background
    schedule: at 3am every day

# Other recurring job examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
